server:
  port: 8880
spring:
  application:
    name: registry
eureka:
  client:
    service-url: #EurekaServer的地址，现在是自己的地址，如果是集群，需要写其它Server的地址
      defaultZone: http://localhost:${server.port}/eureka #注册的地址，如果是集群，应该用,隔开
    register-with-eureka: false #不注册自己
    fetch-registry: false #不拉取服务
