logging:
  config: classpath:log/logback-local.xml
server:
  host: localhost
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://${server.host}:3306/sample_admin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: data
      password: datapwd
    mongo:
      uri: mongodb://data:datapwd@${server.host}:27017/sample_log
tnxjee:
  profile:
    formal: false
  web:
    servlet:
      context:
        attributes:
          tnxweb: //${server.host}/tnxweb
tnxjeex:
  fss:
    accessor:
      local-root: E:\kit\fss\sample