server:
  port: 8881
  servlet:
    context-path: /sample-admin
spring:
  application:
    name: ms-admin
  profiles:
    active: local
  jpa:
    mapping-resources: META-INF/jpa/*.xml
    open-in-view: true
  servlet:
    multipart:
      maxFileSize: -1
  mvc:
    pathmatch:
      use-suffix-pattern: true
    view:
      prefix: /pages/
      suffix: .jsp
    static-path-pattern: /assets/**,/third/**,/pages/**/*.css,/pages/**/*.js,/robots.txt
  resources:
    static-locations: /pages/
