server:
  port: 8881
  servlet:
    context-path: /sample-admin
spring:
  application:
    name: ms-admin
  profiles:
    active: local
  jpa:
    open-in-view: true
  servlet:
    multipart:
      maxFileSize: -1
  mvc:
    pathmatch:
      use-suffix-pattern: true
    view:
      prefix: /pages/
      suffix: .jsp
  resources:
    static-locations: /assets/,/third/,/pages/,/webjars/ #静态资源映射目录
tnxjee:
  web:
    view:
      resource:
        static-patterns: > #静态资源路径样式，满足样式的资源将作为静态资源处理
          /assets/**, /third/**, /pages/**/*.css, /pages/**/*.js, /robots.txt,
          /swagger-ui.html, /webjars/**
