server:
  port: 8881
  servlet:
    context-path: /sample-admin
spring:
  application:
    name: ms-admin
  profiles:
    active: local
  servlet:
    multipart:
      maxFileSize: -1
  mvc:
    pathmatch:
      use-suffix-pattern: true
    view:
      prefix: /pages/
      suffix: .jsp
  resources:
    static-locations: /assets/,/third/,/pages/,/robots.txt
tnxjee:
  web:
    controller:
      servlet:
        context:
          properties: tnxweb.context
    view:
      resources:
        static-pattern: /assets/**, /third/**, /pages/**/*.css, /pages/**/*.js, /robots.txt
seata:
  enabled: true
  tx-service-group: tx_group_sample
  registry:
    type: file
  config:
    type: file
  transport:
    #tcp udt unix-domain-socket
    type: TCP
    #NIO NATIVE
    server: NIO
    #enable heartbeat
    heartbeat: true
    #the client batch send request enable
    enable-client-batch-send-request: true
    #thread factory for netty
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      #netty boss thread size,will not be used for UDT
      boss-thread-size: 1
      #auto default pin or 8
      worker-thread-size: 8
    shutdown:
      #when destroy server, wait seconds
      wait: 3
    serialization: seata
    compressor: none
  service:
    #transaction service group mapping
    vgroup-mapping: tx_group_sample
    #only support when registry.type=file, please don't set multiple addresses
    grouplist: 127.0.0.1:8091
    #degrade, current not support
    enable-degrade: false
    #disable seata
    disable-global-transaction: false
  client:
    rm-async-commit-buffer-limit: 10000
    rm:
      lock:
        lock-retry-interval: 10
        lock-retry-times: 30
        lock-retry-policy-branch-rollback-on-conflict: true
    rm-report-retry-count: 5
    rm-report-success-enable: true
    rm-table-meta-check-enable: false
    tm-commit-retry-count: 5
    tm-rollback-retry-count: 5
    undo:
      undo-data-validation: true
      undo-log-serialization: jackson
      undo-log-table: undo_log
    log:
      exception-rate: 100
    support:
      spring:
        datasource-autoproxy: false