server:
  port: 8881
  servlet:
    context-path: /sample-admin
spring:
  application:
    name: ms-admin
  profiles:
    active: local
  servlet:
    multipart:
      maxFileSize: -1
  mvc:
    pathmatch:
      use-suffix-pattern: true
    view:
      prefix: /pages/
      suffix: .jsp
  resources:
    static-locations: /assets/,/third/,/pages/,/robots.txt
tnxjee:
  web:
    controller:
      servlet:
        context:
          properties: tnxweb.context
    view:
      resources:
        static-pattern: /assets/**, /third/**, /pages/**/*.css, /pages/**/*.js, /robots.txt
