logging:
  config: classpath:log/logback-local.xml
tnxjee:
  profile:
    formal: false
tnxjeex:
  unstructured:
    accessor:
      local_root: E:\kit\unstructured\sample
server:
  host: localhost
  servlet:
    jsp:
      init-parameters:
        development: true
spring:
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://${server.host}:3306/example_admin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: data
    password: datapwd
    mongo:
      uri: mongodb://data:datapwd@${server.host}:27017/example_log
tnxweb:
  context: //${server.host}/tnxweb