server:
  port: 8887
spring:
  application:
    name: ms-admin-api
  profiles:
    active: local
  session:
    store-type: mongodb
tnxjee:
  web:
    cors:
      path-pattern: /**
      allow-credentials: true
      allowed-headers: "*"
      allowed-methods: "*"