server:
  servlet:
    jsp:
      init-parameters:
        development: true
tnxjee:
  web:
    servlet:
      context:
        attributes:
          tnxweb: //localhost/tnxweb
    api:
      base-url: http://localhost:8886
