server:
  port: 8885
spring:
  application:
    name: ms-facade-view
  profiles:
    active: local
  mvc:
    pathmatch:
      use-suffix-pattern: true
    view:
      prefix: /pages/
      suffix: .jsp
    static-path-pattern: /assets/**,/third/**,/pages/**/*.css,/pages/**/*.js,/robots.txt
  resources:
    static-locations: /pages/
  session:
    store-type: mongodb
tnxjee:
  web:
    security:
      csrf-disabled: true
