# common
logging:
  config: classpath:log/logback-local.xml
server:
  servlet:
    jsp:
      init-parameters:
        development: true
host:
  cas: localhost:8883
  facade-view: localhost:8885
  facade-api: localhost:8886
  admin-view: localhost:8887
  admin-api: localhost:8888
  fss: localhost:8889
tnxjee:
  profile:
    formal: false
  common:
    apps:
      cas:
        https: false
        host: ${host.cas}
        context-path: /cas
      facade-view:
        user-type: customer
        https: false
        host: ${host.facade-view}
      facade-api:
        user-type: customer
        https: false
        host: ${host.facade-api}
      admin-view:
        user-type: manager
        https: false
        host: ${host.admin-view}
      admin-api:
        user-type: manager
        https: false
        host: ${host.admin-api}
      fss:
        https: false
        host: ${host.fss}
  web:
    cors:
      allowed-origins:
        - http://localhost:8080
        - http://localhost:8087
tnxjeex:
  cas:
    server-app-name: cas