# common
logging:
  config: classpath:log/logback-local.xml
server:
  servlet:
    jsp:
      init-parameters:
        development: true
tnxjee:
  profile:
    formal: false
  gatway-uri: http://localhost:8880
  common:
    apps:
      cas:
        user-type: '*'
        uri: http://localhost:8883
        context-path: /cas
      facade:
        user-type: customer
        uri: http://localhost:8885
        context-path: ''
      admin:
        user-type: manager
        uri: http://localhost:8887
        context-path: /admin
      fss:
        user-type: '*'
        uri: http://localhost:8889
        context-path: /fss
  web:
    cors:
      allowed-origins:
        - http://localhost:8085
        - http://localhost:8087
tnxjeex:
  cas:
    server-app-name: cas