# common
logging:
  config: classpath:log/logback-local.xml
server:
  servlet:
    jsp:
      init-parameters:
        development: true
tnxjee:
  profile:
    formal: false
  web:
    common:
      apps:
        cas:
          https: false
          host: localhost:8883
        customer-view:
          user-type: customer
          https: false
          host: localhost:8885
        customer-api:
          user-type: customer
          https: false
          host: localhost:8886
        admin-view:
          user-type: manager
          https: false
          host: localhost:8887
        admin-api:
          user-type: manager
          https: false
          host: localhost:8888
        fss:
          https: false
          host: localhost:8889
    cors:
      allowed-origins:
        - http://localhost:8080
        - http://localhost:8087
tnxjeex:
  cas:
    server-url-prefix: http://${tnxjee.micro.service.cas}/cas