# common
logging:
  config: classpath:log/logback-local.xml
server:
  servlet:
    jsp:
      init-parameters:
        development: true
tnxjee:
  profile:
    formal: false
  common:
    apps:
      gateway:
        https: false
        host: localhost:8880
        context-path: ''
      cas:
        user-type: '*'
        https: false
        host: localhost:8883
        context-path: /cas
      facade:
        user-type: customer
        https: false
        host: localhost:8885
        context-path: ''
      admin:
        user-type: manager
        https: false
        host: localhost:8887
        context-path: /admin
      fss:
        user-type: '*'
        https: false
        host: localhost:8889
        context-path: /fss
  web:
    cors:
      allowed-origins:
        - http://localhost:8085
        - http://localhost:8087
tnxjeex:
  cas:
    server-app-name: cas