# common
logging:
  config: classpath:META-INF/log/logback-local.xml
server:
  servlet:
    jsp:
      init-parameters:
        development: true
tnxjee:
  profile:
    formal: false
  common:
    gateway-enabled: false
    gateway-uri: http://localhost:8880
    apps:
      cas:
        user-type: '*'
        direct-uri: http://localhost:8883
        context-path: /cas
      root:
        user-type: customer
        direct-uri: http://localhost:8885
        context-path: ''
      admin:
        user-type: manager
        direct-uri: http://localhost:8887
        context-path: /admin
      fss:
        user-type: '*'
        direct-uri: http://localhost:8889
        context-path: /fss
  web:
    cors:
      allowed-origins:
        - http://localhost:8085
        - http://localhost:8087
