# common
logging:
  config: classpath:log/logback-local.xml
server:
  servlet:
    jsp:
      init-parameters:
        development: true
host:
  cas: localhost:8883
  facade: localhost:8885
  admin: localhost:8887
  fss: localhost:8889
tnxjee:
  profile:
    formal: false
  common:
    apps:
      cas:
        user-type: '*'
        https: false
        host: ${host.cas}
        context-path: /cas
      facade:
        user-type: customer
        https: false
        host: ${host.facade}
      admin:
        user-type: manager
        https: false
        host: ${host.admin}
      fss:
        user-type: '*'
        https: false
        host: ${host.fss}
  web:
    cors:
      allowed-origins:
        - http://localhost:8080
        - http://localhost:8087
tnxjeex:
  cas:
    server-app-name: cas