zuul:
  routes:
    ms-facade:
      path: /**
      url: http://localhost:8886
    ms-admin-api:
      path: /admin-api/**
      url: http://localhost:8887/admin-api
    ms-admin-view:
      path: /admin/**
      url: http://localhost:8888/admin
